"""The public portfolio replay contract.

One account, one causal chronology, one canonical result. Everything a caller
needs to build a replay request, hash it, transport it, and read the result is
exported here; internal helpers stay behind their modules.
"""

from nakagai.engine.canonical import (
    canonical_replay_bytes,
    decode_replay_request,
    decode_replay_result,
    decode_replay_schedule,
    definition_digest,
    encode_replay_request,
    encode_replay_result,
    encode_replay_schedule,
    expected_candidate_id,
    expected_replay_id,
    rejection_id,
    result_digest,
    schedule_digest,
    trade_id,
)
from nakagai.engine.portfolio_types import (
    AccountPolicy,
    BenchmarkResult,
    BenchmarkSpec,
    EntryIntent,
    EquityPoint,
    ExchangeScheduleIdentity,
    ExecutionPolicy,
    ExitReason,
    FeeSpec,
    IcEstimate,
    JSONScalar,
    JSONValue,
    ManagementDecision,
    PlayRequest,
    PortfolioMetrics,
    PortfolioReplayRequest,
    PortfolioReplayResult,
    PortfolioSlice,
    PortfolioTrade,
    PositionView,
    RejectionReason,
    ReplayInputError,
    ReplayRejection,
    ReplaySchedule,
    ReplayWindow,
    ScheduledBaseInterval,
    ScheduledContextBar,
    Signal,
    SlippageSpec,
    StrategyOutputError,
    StrategyRuntimeError,
    TradeStats,
)

__all__ = [
    "AccountPolicy",
    "BenchmarkResult",
    "BenchmarkSpec",
    "EntryIntent",
    "EquityPoint",
    "ExchangeScheduleIdentity",
    "ExecutionPolicy",
    "ExitReason",
    "FeeSpec",
    "IcEstimate",
    "JSONScalar",
    "JSONValue",
    "ManagementDecision",
    "PlayRequest",
    "PortfolioMetrics",
    "PortfolioReplayRequest",
    "PortfolioReplayResult",
    "PortfolioSlice",
    "PortfolioTrade",
    "PositionView",
    "RejectionReason",
    "ReplayInputError",
    "ReplayRejection",
    "ReplaySchedule",
    "ReplayWindow",
    "ScheduledBaseInterval",
    "ScheduledContextBar",
    "Signal",
    "SlippageSpec",
    "StrategyOutputError",
    "StrategyRuntimeError",
    "TradeStats",
    "canonical_replay_bytes",
    "decode_replay_request",
    "decode_replay_result",
    "decode_replay_schedule",
    "definition_digest",
    "encode_replay_request",
    "encode_replay_result",
    "encode_replay_schedule",
    "expected_candidate_id",
    "expected_replay_id",
    "rejection_id",
    "result_digest",
    "schedule_digest",
    "trade_id",
]
